header:
  version: 17

distro: ircam
target: ircam-viewer-image

repos:
  bitbake:
    url: https://git.openembedded.org/bitbake
    branch: master
    layers:
      .: excluded

  openembedded-core:
    url: https://git.openembedded.org/openembedded-core
    branch: master
    layers:
      meta:

  meta-openembedded:
    url: https://git.openembedded.org/meta-openembedded
    branch: master
    layers:
      meta-oe:
      meta-python:

  meta-ircam-viewer:
    layers:
      .:

local_conf_header:
  ffmpeg-license: |
    # Only ffv1 and matroska are used in libav, neither requires licensing. All
    # optional features which require licensing are disabled in PACKAGECONFIG.
    LICENSE_FLAGS_ACCEPTED += "commercial_ffmpeg"

  imagefstypes: |
    IMAGE_FSTYPES = "wic"

  dldir: |
    DL_DIR = "/var/tmp/yocto_dl"
    BB_GENERATE_SHALLOW_TARBALLS = "1"
    BB_GENERATE_MIRROR_TARBALLS = "1"
    BB_GIT_SHALLOW = "1"

  diskmon: |
    BB_DISKMON_DIRS = " \
      STOPTASKS,${TMPDIR},1G,100K \
      STOPTASKS,${DL_DIR},1G,100K \
      STOPTASKS,${SSTATE_DIR},1G,100K \
      STOPTASKS,/tmp,100M,100K \
      HALT,${TMPDIR},100M,1K \
      HALT,${DL_DIR},100M,1K \
      HALT,${SSTATE_DIR},100M,1K \
      HALT,/tmp,10M,1K"
