header:
  version: 17

defaults:
  repos:
    branch: master

env:
  BB_NUMBER_THREADS: null
  PARALLEL_MAKE: null

repos:
  bitbake:
    url: https://git.openembedded.org/bitbake
    layers:
      .: excluded

  openembedded-core:
    url: https://git.openembedded.org/openembedded-core
    layers:
      meta:

  meta-openembedded:
    url: https://git.openembedded.org/meta-openembedded
    layers:
      meta-oe:

  meta-yocto:
    url: https://git.yoctoproject.org/meta-yocto
    layers:
      meta-yocto-bsp:

  meta-raspberrypi:
    url: https://git.yoctoproject.org/meta-raspberrypi
    layers:
      .:

  meta-ircam-viewer:
    layers:
      .:

local_conf_header:
  ffmpeg-license: |
    LICENSE_FLAGS_ACCEPTED:append = " commercial_ffmpeg synaptics-killswitch"

  dldir: |
    DL_DIR = "/var/tmp/yocto_dl"
    BB_GENERATE_SHALLOW_TARBALLS = "1"
    BB_GENERATE_MIRROR_TARBALLS = "1"
    BB_GIT_SHALLOW = "1"

  diskmon: |
    BB_DISKMON_DIRS = " \
      STOPTASKS,${TMPDIR},1G,100K \
      STOPTASKS,${DL_DIR},1G,100K \
      STOPTASKS,${SSTATE_DIR},1G,100K \
      STOPTASKS,/tmp,100M,100K \
      HALT,${TMPDIR},100M,1K \
      HALT,${DL_DIR},100M,1K \
      HALT,${SSTATE_DIR},100M,1K \
      HALT,/tmp,10M,1K"
